version: '3'

services:
  server:
    platform: linux/amd64
    container_name: server
    hostname: server
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - kafka
      - postgres
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    platform: linux/amd64
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'register_student:1:1'
    volumes:
      - /usr/lib/systemd/system/podman.socket:/var/run/docker.sock
  postgres:
    container_name: postgres
    hostname: postgres
    platform: linux/amd64
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
