version: '3'

services:
  nats:
    platform: linux/amd64
    image: nats
    ports:
      - '8222:8222'
      - '4222:4222'
    hostname: nats
    container_name: nats
  postgres:
    container_name: postgres
    hostname: postgres
    platform: linux/amd64
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - '27017:27017'
