version: '3'

services:
  server:
    platform: linux/amd64
    container_name: server
    hostname: server
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - kafka
      - postgres
    networks:
      - app
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    platform: linux/amd64
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - app

  kafka:
    container_name: kafka
    hostname: kafka
    platform: linux/amd64
    image: wurstmeister/kafka:2.11-1.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - app
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'register_student:1:1'
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    volumes:
      - /usr/lib/systemd/system/podman.socket:/var/run/docker.sock
  postgres:
    container_name: postgres
    hostname: postgres
    platform: linux/amd64
    image: postgres
    networks:
      - app
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  app:
    driver: bridge
